database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
  sslmode: disable

neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "password"
  database: "neo4j"

llm:
  provider: openai
  base_url: "https://api.minimaxi.com/v1"
  api_key: "your_openai_api_key_here"
  model: "your-model"

embedding:
  provider: ollama
  base_url: "http://localhost:11434"
  api_key: "your_openai_api_key_here"
  model: "qwen3-embedding:0.6b"
  dimension: 1024

web_search:
    tavily_api_key: